---
title: "proj 2"
output: html_document
---

## R Markdown
# run libraries 
```{r}
library(shiny)
library(choroplethr) 
library(dplyr)
library(leaflet)
library(maps)
library(rgdal)
library(stringr)
library(shinydashboard)
library(tidyverse)
library(tidyr)
library(naniar)
```


```{r}
load('../output/School_Locations.RData')
QR <- read_csv('../data/2005_-_2019_Quality_Review_Ratings.csv')


#SL <- School_Locations%>%filter(Status_descriptions=='Open')%>%
 # select(location_code,location_name,location_type_description,Location_Category_Description,
         #primary_address_line_1,LONGITUDE,LATITUDE)

QR_1519 <- QR%>%
  filter(Start_Date>='2015-01-01')%>%
  select(BN,School_Year,Indicator_1.1,Indicator_1.2,Indicator_1.3,Indicator_1.4,
         Indicator_2.2,Indicator_3.1,Indicator_3.4,Indicator_4.1,Indicator_4.2,Indicator_5.1)

```

```{r}
bn_sl <- SL %>% select (BN, location_name)
QR_1519 <- QR_1519 %>%  inner_join(bn_sl, by = c('BN'='BN')) 


QR_1519_rename <- QR_1519 %>% rename("Curriculum" = "Indicator_1.1", 
                   "Pedagogy" = "Indicator_1.2",
                   "Leveraging_Resources" = "Indicator_1.3",
                   "Positive_Learning_Environment" = "Indicator_1.4",
                   "Assessment" = "Indicator_2.2",
                   "Goals_and_Action_Plans" = "Indicator_3.1",
                   "High_Expectations" = "Indicator_3.4",
                   "Teacher_Support_Supervision" = "Indicator_4.1",
                   "Teacher_Team_Leadership_Development" = "Indicator_4.2", 
                   "Monitoring_Revising_Systems" = "Indicator_5.1"
                   ) %>%
  replace_with_na_all(condition = ~.x=='No Data')%>%
  select(BN,location_name,School_Year,Curriculum,Pedagogy,Leveraging_Resources,
         Positive_Learning_Environment,Assessment,Goals_and_Action_Plans,
         High_Expectations,Teacher_Support_Supervision,Teacher_Team_Leadership_Development,
         Monitoring_Revising_Systems) %>% 
  mutate (Curriculum = factor(Curriculum),Pedagogy = factor(Pedagogy),
          Leveraging_Resources = factor(Leveraging_Resources),
          Positive_Learning_Environment = factor(Positive_Learning_Environment),
         Assessment = factor(Assessment),Goals_and_Action_Plans = factor(Goals_and_Action_Plans),
         High_Expectations = factor(High_Expectations),
         Teacher_Support_Supervision = factor(Teacher_Support_Supervision),
         Teacher_Team_Leadership_Development = factor(Teacher_Team_Leadership_Development),
         Monitoring_Revising_Systems = factor(Monitoring_Revising_Systems), 
         # change to rating 1 to 5 
         Curriculum = fct_recode(Curriculum, "1" = "U", "1" = "UD", "2" = "UPF", "3" = "D", 
                                 "4" = "P", "5" = "WD", "6" = "O"), 
          Pedagogy = fct_recode(Pedagogy, "1" = "U", "1" = "UD", "2" = "UPF", "3" = "D", 
                                "4" = "P", "5" = "WD", "6" = "O"),
          Leveraging_Resources = fct_recode(Leveraging_Resources, "1" = "U", "1" = "UD", "2" = "UPF", 
                                            "3" = "D", "4" = "P", "5" = "WD", "6" = "O"),
          Positive_Learning_Environment = fct_recode(Positive_Learning_Environment, 
                                                    "1" = "U", "1" = "UD","2" = "UPF", "3" = "D", 
                                                    "4" = "P", "5" = "WD", "6" = "O"),
         Assessment = fct_recode(Assessment, "1" = "U", "1" = "UD", "2" = "UPF", "3" = "D", 
                                 "4" = "P", "5" = "WD", "6" = "O"),
         Goals_and_Action_Plans = fct_recode(Goals_and_Action_Plans, "1" = "U", "1" = "UD", "2" = "UPF",
                                             "3" = "D", "4" = "P", "5" = "WD", "6" = "O"),
         High_Expectations = fct_recode(High_Expectations, "1" = "U", "1" = "UD", "2" = "UPF", "3" = "D",
                                        "4" = "P", "5" = "WD", "6"= "O"),
         Teacher_Support_Supervision = fct_recode(Teacher_Support_Supervision, "1" = "U", "1" = "UD", 
                                                  "2" = "UPF", "3" = "D", "4" = "P", 
                                                  "5" = "WD", "6" = "O"),
         Teacher_Team_Leadership_Development = fct_recode(Teacher_Team_Leadership_Development, 
                                                          "1" = "U", "1" = "UD", "2" = "UPF", "3" = "D",
                                                          "4" = "P", "5" = "WD", "6" = "O"),
         Monitoring_Revising_Systems = fct_recode(Monitoring_Revising_Systems, "1" = "U", "1" = "UD",
                                                  "2" = "UPF", "3" = "D", "4" = "P", 
                                                  "5" = "WD", "6" = "O")) %>%
  pivot_wider(names_from = School_Year,values_from=c(Curriculum:Monitoring_Revising_Systems))%>%
  unnest()
save(QR_1519_rename, file="../output/QR_1519_rename.RData")
```

```{r}
SS_17 <- read_csv('../data/School Survey 2017.csv')
SS_18 <- read_csv('../data/School Survey 2018.csv')
SS_19 <- read_csv('../data/School Survey 2019.csv')
SS_17 <- SS_17%>%select(DBN,`School Name`,`Collaborative Teachers Score`:`Trust Score`)%>%
  replace_with_na_all(condition = ~.x=='N/A')%>%
  filter_all(any_vars(!is.na(.)))%>%
  rename('17 Collaborative Teachers Score'='Collaborative Teachers Score',
                        '17 Effective School Leadership Score'=
                          'Effective School Leadership Score',
                        '17 Rigorous Instruction Score'='Rigorous Instruction Score',
                        '17 Supportive Environment Score'='Supportive Environment Score',
                        '17 Strong Family-Community Ties Score'=
                          'Strong Family-Community Ties Score',
                        '17 Trust Score'='Trust Score')
SS_18 <- SS_18%>%select(DBN,`Collaborative Teachers Score`:`Trust Score`)%>%
  replace_with_na_all(condition = ~.x=='N/A')%>%
  filter_all(any_vars(!is.na(.)))%>%
  rename('18 Collaborative Teachers Score'='Collaborative Teachers Score',
                        '18 Effective School Leadership Score'=
                          'Effective School Leadership Score',
                        '18 Rigorous Instruction Score'='Rigorous Instruction Score',
                        '18 Supportive Environment Score'='Supportive Environment Score',
                        '18 Strong Family-Community Ties Score'=
                          'Strong Family-Community Ties Score',
                        '18 Trust Score'='Trust Score')
SS_19 <- SS_19%>%select(DBN,`Collaborative Teachers Score`:`Trust Score`)%>%
  replace_with_na_all(condition = ~.x=='N/A')%>%
  filter_all(any_vars(!is.na(.)))%>%
  rename('19 Collaborative Teachers Score'='Collaborative Teachers Score',
                        '19 Effective School Leadership Score'=
                          'Effective School Leadership Score',
                        '19 Rigorous Instruction Score'='Rigorous Instruction Score',
                        '19 Supportive Environment Score'='Supportive Environment Score',
                        '19 Strong Family-Community Ties Score'=
                          'Strong Family-Community Ties Score',
                        '19 Trust Score'='Trust Score')
SS <- SS_17%>%inner_join(SS_18,by='DBN')%>%
  inner_join(SS_19,by='DBN')%>%inner_join(select(SL,DBN),by='DBN')
save(SS, file="../output/School_Survey17-19.RData")
```

```{r}
demographic_by_borough <- read_csv('../data/demographic/demographic_by_borough.csv')
demographic_by_citywide <- read_csv('../data/demographic/demographic_by_citywide.csv')
demographic_by_school <- read_csv('../data/demographic/demographic_by_school.csv')
demographic_by_district <- read_csv('../data/demographic/demographic_by_district.csv')
```

# category elementary, middle and high school 
```{r}
demographic_by_school$gradeLevel <- NA
demographic_by_school$gradeLevel[demographic_by_school$`Grade 1` == 0 & demographic_by_school$`Grade 6` == 0 & demographic_by_school$`Grade 9` == 0] <- "no records" 

demographic_by_school$gradeLevel[demographic_by_school$`Grade 1` != 0 & demographic_by_school$`Grade 6` == 0 & demographic_by_school$`Grade 9` == 0] <- "elementary" 
demographic_by_school$gradeLevel[demographic_by_school$`Grade 1` != 0 & demographic_by_school$`Grade 6` != 0 & demographic_by_school$`Grade 9` == 0] <- "elementary, middle" 
demographic_by_school$gradeLevel[demographic_by_school$`Grade 1` != 0 & demographic_by_school$`Grade 6` != 0 & demographic_by_school$`Grade 9` != 0] <- "elementary, middle, high" 


demographic_by_school$gradeLevel[demographic_by_school$`Grade 1` == 0 & demographic_by_school$`Grade 6` != 0 & demographic_by_school$`Grade 9` == 0] <- "middle" 
demographic_by_school$gradeLevel[demographic_by_school$`Grade 1` == 0 & demographic_by_school$`Grade 6` != 0 & demographic_by_school$`Grade 9` != 0] <- "middle, high" 


demographic_by_school$gradeLevel[demographic_by_school$`Grade 1` == 0 & demographic_by_school$`Grade 6` == 0 & demographic_by_school$`Grade 9` != 0] <- "high" 
demographic_by_school$gradeLevel[demographic_by_school$`Grade 1` != 0 & demographic_by_school$`Grade 6` == 0 & demographic_by_school$`Grade 9` != 0] <- "elementary, high" 
demographic_by_school <- demographic_by_school %>% inner_join(bn_sl, by = c('School Name' = 'location_name'))

save(demographic_by_school, file="../output/demographic_by_school.RData")

```


