---
title: "proj 2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
# run libraries 
```{r}
library(shiny)
library(choroplethr)
library(dplyr)
library(leaflet)
library(maps)
library(rgdal)
library(stringr)
library(shinydashboard)
library(tidyverse)
library(tidyr)
```


```{r}
load('../output/School_Locations.RData')
QR <- read_csv('../data/2005_-_2019_Quality_Review_Ratings.csv')
SS_17 <- read_csv('../data/School Survey 2017.csv')


SL <- School_Locations%>%filter(Status_descriptions=='Open')%>%
  select(location_code,location_name,location_type_description,Location_Category_Description,
         primary_address_line_1,LONGITUDE,LATITUDE)
QR_1519 <- QR%>%
  filter(Start_Date>='2015-01-01')%>%
  select(BN,School_Year,Indicator_1.1,Indicator_1.2,Indicator_1.3,Indicator_1.4,
         Indicator_2.2,Indicator_3.1,Indicator_3.4,Indicator_4.1,Indicator_4.2,Indicator_5.1)
QR_1519$BN
bn_sl <- SL %>% select (location_code, location_name)
QR_1519 %>%  merge(bn_sl, by.x=c("BN"),
    by.y=c("location_code")) %>% 
  select(BN,location_name, School_Year,Indicator_1.1,Indicator_1.2,Indicator_1.3,Indicator_1.4,
         Indicator_2.2,Indicator_3.1,Indicator_3.4,Indicator_4.1,Indicator_4.2,Indicator_5.1)
head(SS_17)
```

```{r}
demographic_by_borough <- read_csv('../data/demographic/demographic_by_borough.csv')
demographic_by_citywide <- read_csv('../data/demographic/demographic_by_citywide.csv')
demographic_by_school <- read_csv('../data/demographic/demographic_by_school.csv')
demographic_by_district <- read_csv('../data/demographic/demographic_by_district.csv')



```

# category elementary, middle and high school 
```{r}
demographic_by_school$gradeLevel <- NA
demographic_by_school$gradeLevel[demographic_by_school$`Grade 1` == 0 & demographic_by_school$`Grade 6` == 0 & demographic_by_school$`Grade 9` == 0] <- "no records" 

demographic_by_school$gradeLevel[demographic_by_school$`Grade 1` != 0 & demographic_by_school$`Grade 6` == 0 & demographic_by_school$`Grade 9` == 0] <- "elementary" 
demographic_by_school$gradeLevel[demographic_by_school$`Grade 1` != 0 & demographic_by_school$`Grade 6` != 0 & demographic_by_school$`Grade 9` == 0] <- "elementary, middle" 
demographic_by_school$gradeLevel[demographic_by_school$`Grade 1` != 0 & demographic_by_school$`Grade 6` != 0 & demographic_by_school$`Grade 9` != 0] <- "elementary, middle, high" 


demographic_by_school$gradeLevel[demographic_by_school$`Grade 1` == 0 & demographic_by_school$`Grade 6` != 0 & demographic_by_school$`Grade 9` == 0] <- "middle" 
demographic_by_school$gradeLevel[demographic_by_school$`Grade 1` == 0 & demographic_by_school$`Grade 6` != 0 & demographic_by_school$`Grade 9` != 0] <- "middle, high" 


demographic_by_school$gradeLevel[demographic_by_school$`Grade 1` == 0 & demographic_by_school$`Grade 6` == 0 & demographic_by_school$`Grade 9` != 0] <- "high" 
demographic_by_school$gradeLevel[demographic_by_school$`Grade 1` != 0 & demographic_by_school$`Grade 6` == 0 & demographic_by_school$`Grade 9` != 0] <- "elementary, high" 


save(demographic_by_school, file="../output/demographic_by_school.RData")

```

